backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

site_url: https://bceffretikon.markwalder.eu

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: packages/website/static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
    - name: 'blog' # Used in routes, e.g., /admin/collections/blog
      label: 'Blog' # Used in the UI
      folder: 'packages/website/static/posts' # The path to the folder where our blog posts are stored
      create: true # Allow users to create new documents in this collection
      fields: # The fields for each document
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Abstract', name: 'abstract', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'data'
      label: 'Data'
      files:
          - name: 'holidays'
            label: 'Holidays'
            file: 'packages/website/static/holidays.yml'
            fields:
                - name: 'holiday'
                  label: 'Holiday'
                  widget: 'list'
                  fields:
                      - { label: Title (DE), name: title-de, widget: string }
                      - { label: Title (EN), name: title-en, widget: string }
                      - { label: Title (FR), name: title-fr, widget: string }
                      - { label: Title (IT), name: title-it, widget: string }
                      - { label: 'From', name: 'from', widget: 'string' }
                      - { label: 'To', name: 'to', widget: 'string' }
