service: bceffretikon-website

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x

functions:

  # CloudFormation resource templates here
resources:
  # S3
  - ${file(resources/s3-bucket.yml)}
  # CloudFront
  - ${file(resources/cloudfront.yml)}
  # CodeBuild
  - ${file(resources/codebuild.yml)}
  # CodePipeline
  - ${file(resources/codepipeline.yml)}
